apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: externalmodulesources.deckhouse.io
  labels:
    heritage: deckhouse
    module: external-module-manager
spec:
  group: deckhouse.io
  scope: Cluster
  names:
    plural: externalmodulesources
    singular: externalmodulesource
    kind: ExternalModuleSource
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: |
            Defines the configuration.
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - version
              properties:
                registry:
                  type: object
                  properties:
                    repo:
                      type: string
                    dockerCfg:
                      type: string
            status:
              type: object
              properties:
                syncTime:
                  type: string
                  description: Time of release status change.
                availableModules:
                  type: array
                  items:
                    type: string
                message:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: syncTime
          jsonPath: .status.syncTime
          type: date
          format: date-time
          description: 'When the release status was changed.'
